// <auto-generated />
namespace Movie_recommendation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Edited_Movie_ID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edited_Movie_ID));
        
        string IMigrationMetadata.Id
        {
            get { return "201905112030422_Edited_Movie_ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
